x = input("digite alguma coisa: ")
print( "O tipo desse valor é:", type(x))
print("É apenas alfabético? ",x.isalpha())
print("É apenas numeros? ",x.isnumeric())
print("É alfa numérico? ",x.isalnum())
print("É apenas digitos? ",x.isdigit())
print("É um valor decimal? ",x.isdecimal())
print("É um identificador?  ",x.isidentifier())
print("É imprimível? ",x.isprintable())
print("É maiusculo?  ",x.isupper())
print("É minusculo?  ",x.islower())
print("Está captalizada?  ",x.istitle())